# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/Tex/PycharmProjects/Green_AI/project/user_interface/Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.Calculator = QtWidgets.QPushButton(Form)
        self.Calculator.setGeometry(QtCore.QRect(280, 240, 81, 26))
        self.Calculator.setObjectName("Calculator")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(160, 50, 60, 16))
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(280, 50, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.dial = QtWidgets.QDial(Form)
        self.dial.setGeometry(QtCore.QRect(50, 150, 50, 64))
        self.dial.setObjectName("dial")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(200, 130, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(40, 80, 81, 22))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Calculator.setText(_translate("Form", "Calculate"))
        self.label.setText(_translate("Form", "GreenAI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
